import Head from 'next/head';
import Header from '../Header/Header';
import LoginPage from '../Login/LoginPage';
import Sidebar from '../Sidebar/Sidebar';
import withAuthAdmin from '@/hoc/withAuthAdmin';
import { getIsAdmin } from '@/redux/user';
import { useSelector } from 'react-redux';
import { useEffect, useRef } from 'react';
import { useRouter } from 'next/router';

const Layout = ({ children }) => {
	const login = useSelector(getIsAdmin);
	const mainRef = useRef();
	const router = useRouter();
	useEffect(() => {
		if (!mainRef.current) return;
		mainRef.current.scrollTo({ top: 0 });
	}, [router]);
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{!login && <LoginPage />}
			{login && (
				<div className="bg-slate-200">
					<div className="flex layout-out">
						<Sidebar />
						<div className="flex-1 overflow-scroll hide-scroll">
							<Header />
							<div
								className="layout-in bg-secondary h-[calc(100vh-60px)] overflow-scroll hide-scroll "
								ref={mainRef}
							>
								{children}
							</div>
						</div>
					</div>
				</div>
			)}
		</>
	);
};

export default withAuthAdmin(Layout);
